# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Appointments',
                'ordering': ['datetime'],
                'verbose_name': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_service.Appointments')),
            ],
            options={
                'verbose_name_plural': 'Dates of event',
                'verbose_name': 'Date of event',
            },
        ),
        migrations.CreateModel(
            name='SubmittedForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_range', models.CharField(max_length=256, verbose_name='Time range')),
                ('full_name', models.CharField(max_length=256, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Submitted forms',
                'verbose_name': 'Submitted form ',
            },
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_service.Appointments')),
            ],
            options={
                'verbose_name_plural': 'Time ranges',
                'verbose_name': 'Time range ',
            },
        ),
    ]
